apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - image: linclaus/python-flask:v0.1.0
        imagePullPolicy: Always
        name: python-flask
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 200Mi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  selector:
    app: python-flask
  type: NodePort
  ports:
  - name: port
    nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080

